### ISSUE TITLE
Mention open_basedir restriction in documentation

### ISSUE THREAD

**Issue by jellewebsols** [christophlehmann/imageoptimizer#10]
Suggestion for the documentation: TYPO3\CMS\Core\Utility\CommandUtility::getCommand uses 'is_executable()' to check if the binaries are present and executable. When a open_basedir restriction is in place, that check fails, although calling the binaries with exec() works fine (at least, in our enviroment).

**Comment by opi99** [comment]
Yes, exec will work also outside open_basedir restrictions.
TIP to get it working:
* Add `$GLOBALS['TYPO3_CONF_VARS']['SYS']['binSetup'] = 'jpegoptim=/usr/bin/jpegoptim,optipng=/usr/bin/optipng,gifsicle=/usr/bin/gifsicle'` to your configuration, then getCommand do not run the "is_executable()" command.

**Comment by christophlehmann** [comment]
I mentioned it in v1.1.0
