### ISSUE TITLE
can you explain?

### ISSUE THREAD

**Issue by maikusch** [christophlehmann/imageoptimizer#11]
hey there...
i installed your ext and have a question.
i enabled logging and in log is this:

/kunden/homepages/28/d574274134/htdocs//kunden/homepages/28/d574274134/htdocs/jpegoptim --strip-all /kunden/homepages/28/d574274134/htdocs/update7/fileadmin/_processed_/e/4/preview_Dialog-Wehling9-web_911423aa83.jpg 2>&1 exited with 127. Output was: sh: 1: /kunden/homepages/28/d574274134/htdocs//kunden/homepages/28/d574274134/htdocs/jpegoptim: not found (msg#4.0.127)

look at the last words "not found".
but the reports say the binary is found and in use. Why is this?

**Comment by christophlehmann** [comment]
The doubled path looks wrong to me. You can try to fix it by using a path in jpgBinary in EM.

**Comment by christophlehmann** [comment]
When you think it's a bug please open another issue.
