### ISSUE TITLE
[TASK] Implement cjpeg-dssim

### ISSUE THREAD

**Issue by dhuf** [christophlehmann/imageoptimizer#12]
No Idea where or how to implement it but I came across this article and thought it would be really nice. https://codeascraft.com/2017/05/30/reducing-image-file-size-at-etsy/

Using: https://github.com/technopagan/cjpeg-dssim 

Or would it even be possible over the "jpegoptim" implementation ?

**Comment by christophlehmann** [comment]
Yes, you can use the tool.

The command is `cjpeg-dssim jpegoptim /path/to/input-image.jpg`, so set the following in the Extension Manager configuration

jpgBinary => cjpeg
jpgParametersOnProcessing => jpegoptim %s

Would you share your results after testing the tool?

**Comment by dhuf** [comment]
Oh thanks for you feedback, we will keep you posted thanks a lot.
