### ISSUE TITLE
[TASK] implement mozjpeg

### ISSUE THREAD

**Issue by DanielRuf** [christophlehmann/imageoptimizer#16]
mozjpeg is bases on libjpeg-turbo, combines several appeoaches and provides smaller progressive images.

Progressive images generally improve the perceived performance and produce better speedindex values.

**Comment by christophlehmann** [comment]
What to do here? :-)

You can use binaries of your choice, see #12

**Comment by DanielRuf** [comment]
Ah right. Sure, then we are free to install any binary that we want. Sorry. I thought there would be more steps needed to support specific binaries, especially when it comes to progressively encoded image generation.

**Comment by DanielRuf** [comment]
So I guess I can also close #17? =)
