### ISSUE TITLE
sharp / libvips

### ISSUE THREAD

**Issue by DanielRuf** [christophlehmann/imageoptimizer#17]
https://github.com/lovell/sharp uses libvips which is ideal for web, provides progressive options, consumes not much memory, ...

One of both might be interesting to have a fast lowmemory image processing solution for web.

**Comment by christophlehmann** [comment]
Currently i don't see any performance issues, but faster sounds better and lower memory usage too.

When i see it correctly sharp has no wrapper script or binary to use. Would you like to provide an example implementation with a wrapper script?

**Comment by DanielRuf** [comment]
Generally sharp can be used with sharp-cli https://github.com/lovell/sharp/blob/master/docs/install.md#cli-tools so I guess the question is already answered.

Did not think so far that we are totally free when it comes to the binary / cli command that is executed.

It's a bit unexpected to be so free and have a solution which has no hard dependencies and does not come bundled with any binaries. =)
