### ISSUE TITLE
[BUG] Log shows duplicated path - Binary not found

### ISSUE THREAD

**Issue by schwardtz** [christophlehmann/imageoptimizer#19]
Hi Christoph, 

I configured the path to the jpgBinary and according to the report Binary /files/bin/jpegoptim can be found. However, simliar to #11 , in the logs the path appears twice. 

`/files/bin//files/bin/optipng -o2 /home/www/******/html/typo3/fileadmin/_processed_/4/d/csm_Lebensmittel_565a6f6af7.png 2>&1 exited with 127. Output was: sh: /files/bin//files/bin/optipng: No such file or directory (msg#4.0.127)`

Any ideas?

**Comment by christophlehmann** [comment]
Hi Johannes,

i) Do you need to set the path to make the Report Happy?
ii) What happens when you set a relative path (without the leading slash)?
iii) what happens without a path and you Put the Binary in the webroot beside Index.php ?

Seems like there is a shell wrapper active...

**Comment by schwardtz** [comment]
Hi Christoph, 
i) the path has to be set to get a positive report. 
ii) a relative path return "Not found"
iii) that works. 

So it's a problem with the server configuration? Thank you for your help!

**Comment by christophlehmann** [comment]
Using a path there (in EM) is probably wrong and we have to correct it.

Please set the binPath/binSetup in install tool and remove the path to your binary in EM. Does it work now?
