### ISSUE TITLE
Trim Error keeps flodding Log file

### ISSUE THREAD

**Issue by discotizer** [christophlehmann/imageoptimizer#20]
Hello Christoph,

thanks for this cool plugin! I've just stumpled upon a nasty thing:
After activating the plugin the error log file (logs only errors!) is being flodded (several hundred lines per minute) with this message over and over:
PHP Warning:  trim() expects parameter 1 to be string, object given in /html/typo3/typo3_src-7.6.23/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php on line 6412

Line 6412 says: "$linkParameter = trim(isset($conf['parameter.']) ? $this->stdWrap($conf['parameter'], $conf['parameter.']) : $conf['parameter']);"
Any idea how to get rid of that? I've turned off repeated errors and sources in PHP but it doesn't helped.

**Comment by christophlehmann** [comment]
Hey, a warning is not an error ;-) And i close this, since your warning has nothing to do with the extension...
