### ISSUE TITLE
[FEATURE] Consider offering zopflipng for PNG-images

### ISSUE THREAD

**Issue by neufeind** [christophlehmann/imageoptimizer#29]
https://github.com/google/zopfli
https://ariya.io/2016/06/using-zopfli-to-optimize-png-images

Compresses PNGs lossless, features some additional switches for optimization.

**Comment by christophlehmann** [comment]
Hi Stefan,

the possible list of tools is long ;-) 

If you like you can add a  table to the Readme "Usage examples with other tools"

| Binary | Parameters | Filetype | Description |
|-----------|------------|----------|--|
| [your tool](https://website-of-your-tool.com) | %s %s | PNG | Lossless, better results than XY but slower |
