### ISSUE TITLE
Error Message not showing missing Binary Name

### ISSUE THREAD

**Issue by bitbruder** [christophlehmann/imageoptimizer#34]
When using imageoptimizer on a system that is missing binaries e.g. jpegoptim, optipng or gifsicle, its just stating that "Binary" was not found. This led to confusion on my part.

```
Core: Exception handler (WEB): 
Uncaught TYPO3 Exception: #1488631746: Binary not found
RuntimeException thrown in file
.../imageoptimizer/Classes/OptimizeImageService.php in line 42. 
Requested URL: https://example.com/.../
```

I guess that the missing Binary should be printed inbetween `Binary {HERE} not found`.

But this is not the case on my system. Am I missing something?

**Comment by christophlehmann** [comment]
Are the test commands successful?
Is the Report-Modul happy?

**Comment by DanielRuf** [comment]
I think casting a non-string to a string in an exception is not the best idea:
https://github.com/christophlehmann/imageoptimizer/blob/master/Classes/OptimizeImageService.php#L77

**Comment by DanielRuf** [comment]
Should be probably https://github.com/christophlehmann/imageoptimizer/blob/master/Classes/OptimizeImageService.php#L82
