### ISSUE TITLE
[FEATURE] add local binaries 

### ISSUE THREAD

**Issue by alrnz** [christophlehmann/imageoptimizer#36]
Hey, thanks for the great plugin.

It would be very cool to have some precompiled binaries shipped with the plugin, like EWWW Image optimizer for WordPress does.
So the plugin would work on more systems/out of the box.

Greetings Arne

**Comment by christophlehmann** [comment]
Hey Arne,

Thanks! Basically it's a good idea, but i would not realize it for the following reasons

* There are hosting providers (also for TYPO3) having the binaries preinstalled
* It's easy to install them through package managers like apt/yum/npm and their maintenance is ~0% once installed
* I would keep it simple stupid :-)
