### ISSUE TITLE
Make extension installable via composer

### ISSUE THREAD

**Issue by Sebobo** [christophlehmann/imageoptimizer#4]
For composer based TYPO3 installations it would be great to have a `composer.json` in the package and have it on packagist.

As we plan to try this package, we could add create the file and provide a merge request.

**Comment by christophlehmann** [comment]
sounds good. Would you like to make a PR?

**Comment by Sebobo** [comment]
Sure, we will try to integrate this package into two projects during the next 2-3 weeks then we can provide that.

**Comment by Sebobo** [comment]
Solved in #5
