### ISSUE TITLE
Call to a member function process() on null

### ISSUE THREAD

**Issue by scriptserv** [christophlehmann/imageoptimizer#42]
Everytime i'm trying to change an image i'm getting the following error:

Call to a member function process() on null
xxxxx\typo3conf\ext\imageoptimizer\Classes\EventListener\AfterFileProcessing.php line 11

When i'm trying to upload an image i'm getting the following error:

Call to a member function process() on null 
Error thrown in file xxxxx\typo3conf\ext\imageoptimizer\Classes\EventListener\BeforeFileAdded.php in line 10

TYPO3 v10.4.2
ImageOptimizer 3.0.0
Windows 10 / Linux (Local and Dev)

The same setup is working fine with TYPO3 9.5.x and ImageOptimizer 2.x
BTW: thanks for your effort, you´re doing a great job!

**Comment by christophlehmann** [comment]
Can you check https://github.com/christophlehmann/imageoptimizer/pull/43 ?
