### ISSUE TITLE
Neuen Tag / Version für Packagist

### ISSUE THREAD

**Issue by mueller-sebastian** [christophlehmann/imageoptimizer#45]
Hallo,
danke für die coole Extension und das du auch schon den Fix in der composer.json gemacht hast (extension-key).
Könntest du hierfür eine neue Version machen bzw. einen Tag erstellen, damit auf Packagist die neue Änderung vorhanden ist? :-)
Vielen Dank

**Comment by dennismetz** [comment]
Gibt es hierzu einen aktuellen Status?
