### ISSUE TITLE
V11 compatible version?

### ISSUE THREAD

**Issue by NeoBlack** [christophlehmann/imageoptimizer#46]
Hi Christoph,
is it possible to prepare a v11 compatible version? dev-master would be fine for testing purposes.
I am trying to update an installation to v11 and I would like to prevent a fork of your extension for a single line of code.

thx

**Comment by christophlehmann** [comment]
Sure, No problem. Can you adapt the ext_emconf.php too? (To make typo3_console happy)

**Comment by NeoBlack** [comment]
Adapted the PR, thx.
