### ISSUE TITLE
PHP 8.1: Missing array key exists check in OptimizeImageService throws exception

### ISSUE THREAD

**Issue by akiessling** [christophlehmann/imageoptimizer#54]
We added webp to our list of image file extensions to generate webp versions directly in fluid templates.
The OptimizeImageService does not check if the config exists and thus throws an exception when it renders the template

> PHP Warning: Undefined array key "webpOnProcessing" in /var/www/html/src/private/typo3conf/ext/imageoptimizer/Classes/OptimizeImageService.php line 70

https://github.com/christophlehmann/imageoptimizer/blob/1571a96963d14a7045a6500987af3ccaca86e921/Classes/OptimizeImageService.php#L70

This should prevent the exception if no configuration is set
```
if (!isset($this->configuration[$extension . 'On' . $when]) || ((bool)$this->configuration[$extension . 'On' . $when] === false && $testMode === false)) {
```

**Comment by christophlehmann** [comment]
Accepted. Would you create a PR?

**Comment by akiessling** [comment]
yep, will do
