### ISSUE TITLE
Exception when WebP Images are created in Fluid

### ISSUE THREAD

**Issue by bavarianbytes** [christophlehmann/imageoptimizer#58]
From time to time this exception pops up in the frontend, when i generate WebP images (out of JPGs) via `<f:image fileExtension="webp">` of `<f:uri.image fileExtension="webp">`.
```
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "webpOnProcessing" in /Users/***/typo3conf/ext/imageoptimizer/Classes/OptimizeImageService.php line 70
```

TYPO3 11.5.13
imageoptimizer 3.1.0

**Comment by christophlehmann** [comment]
Seems fixed with #54
