### ISSUE TITLE
TYPO3 v12 compatibility

### ISSUE THREAD

**Issue by mehdichaouch** [christophlehmann/imageoptimizer#59]
Hello,

Could you tell me if you have plan any update of this nice extension to TYPO3 v12?

Any date for that?

Best,

**Comment by christophlehmann** [comment]
Hey, i have no date for it, yet. A PR is very welcome and will accelerate it. Would you give it a try?

The extension scanner reports, that there are some things to do, some are breaking.

<img width="1361" alt="Bildschirmfoto 2023-07-03 um 22 27 29" src="https://github.com/christophlehmann/imageoptimizer/assets/4953689/34d2cf99-917c-4477-8716-5f7cfe35a3e2">

**Comment by SSFGizmo** [comment]
@christophlehmann, @mehdichaouch Can you please check?

* https://github.com/SSFGizmo/imageoptimizer
* https://github.com/christophlehmann/imageoptimizer/pull/60

**Comment by dennismetz** [comment]
Are there any updates here yet? The extension is really great and I would like to continue using it

**Comment by christophlehmann** [comment]
will check it next week after vacation
