### ISSUE TITLE
I am getting error /usr/bin/jpegoptim: not found

### ISSUE THREAD

**Issue by pitssavinmb** [christophlehmann/imageoptimizer#67]
JPG: /usr/bin/jpegoptim --strip-all '/var/www/html/XXXX/XXXXXX/typo3temp/var/transient/imageoptimizer4052186309425189030jpg' 2>&1
sh: 1: /usr/bin/jpegoptim: not found

JPG on Upload: /usr/bin/jpegoptim --strip-all '/var/www/html/XXXX/XXXXX/typo3temp/var/transient/imageoptimizer5556720757223879253jpg' 2>&1
sh: 1: /usr/bin/jpegoptim: not found.

![error](https://github.com/christophlehmann/imageoptimizer/assets/164833667/f2a3aa4c-1d74-46ae-83f5-cbf6e2564168)

**Comment by simonschaufi** [comment]
Please read the readme and the section "installation".
