### ISSUE TITLE
[BUG] Extension removes = from command

### ISSUE THREAD

**Issue by dgrammlich** [christophlehmann/imageoptimizer#8]
Hi,

we use the extension version 1.0.0 with TYPO3 6.2 and FreeBSD. I've configured the optimization for JPG files with _jpegoptim_ and the following parameters in the extension settings:
`--strip-all --max=80 --all-progressive %s`

But the = is stripped from the command:
![screenshot from 2017-03-09 08-50-03](https://cloud.githubusercontent.com/assets/5312377/23740790/872b7680-04a5-11e7-83fb-00f451030ff1.png)

This works:
`--strip-all -m80 --all-progressive %s`

Regards
Daniela

**Comment by christophlehmann** [comment]
Good hint ;-) Thank you!

Viele Grüße
Christoph
